language: python
python:
#  - "3.4"
#  - "3.5"
#  - "3.7"
#  - "3.8"
  - "3.9"
before_install:
  - python -m pip install --upgrade pip
# install dependencies
install:
  - pip install -r requirements.txt
# run tests
script:
  - pytest